# Generated by Django 2.1.3 on 2018-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181112_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_page',
            name='visit_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
