# Generated by Django 2.1.3 on 2018-11-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_index_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_page',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('visit_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('visit_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
