# Generated by Django 2.1.3 on 2018-11-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_index_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index_page',
        ),
    ]
