# Generated by Django 2.1.3 on 2018-11-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_index_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('read_time', models.DateField(auto_now_add=True, verbose_name='阅读量')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
    ]
