# Generated by Django 2.1.3 on 2018-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
