# Generated by Django 2.1.3 on 2018-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181117_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_read_num',
            field=models.IntegerField(default=0, verbose_name='分类阅读数'),
        ),
    ]
