# Generated by Django 2.1.3 on 2018-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_category_read_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
