# Generated by Django 2.1.3 on 2018-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_category_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='process_color',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
