# Generated by Django 2.1.3 on 2018-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_process_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
