# Generated by Django 2.1.3 on 2018-11-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181118_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_color',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
