# Generated by Django 2.1.3 on 2018-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_category_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_color',
            field=models.CharField(default='label-primary', max_length=32, null=True),
        ),
    ]
