# Generated by Django 2.1.3 on 2018-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181119_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
