# Generated by Django 2.1.3 on 2018-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20181121_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
